### ISSUE TITLE
Non-destructive story creation

### ISSUE THREAD

**Issue by TylersDesk** [hoodoo-digital/acme#18]
When adding a new variation to a story, i.e. a button, we don't want to delete any modifications to the story (thinking of the XD design link).

**Comment by madoni** [comment]
@TylersDesk, now that we're using the "Core Components Examples" to generate stories, will these new variations be added to that project?

**Comment by davekenison** [comment]
I think the idea is that when `acme` generates the stories instead of the commented out storybook url we will have code like this:
```
parameters: {
    design: {
      //artboardUrl: '<Enter the url to the XD artboard corresponding to this story here>'
    }
}
```
And then when `acme` gets run again it only generates stories for new components and leaves any existing components untouched. Not sure how that will work if new stories need to be added to an existing component.
